### ISSUE TITLE
Need to be able to run the program from anywhere

### ISSUE THREAD

**Issue by waldo323** [craigmaloney/pygame_photobooth#10]
Need to be able to run the program from anywhere so when auto starting the paths work ok

**Comment by waldo323** [comment]
I created a separate shell script which simply changes to the photo booth program folder and then runs the capture.py script

**Comment by craigmaloney** [comment]
Would you create a pull request with the shell script? Thanks!

**Comment by craigmaloney** [comment]
Ah, I see what's going on. When it loads the config file if it isn't given an explicit path then it defaults to "./peppercarrot.yaml". So if it's not in the same directory it'll error out.

**Comment by craigmaloney** [comment]
I think this is fixed with the latest push in feature/cleanup. Please confirm.

**Comment by craigmaloney** [comment]
@waldo323 Did this work properly for Penguicon or is there still more work to do?

**Comment by waldo323** [comment]
I can run capture from elsewhere running develop, but run into an issue 

Traceback (most recent call last):
  File "/home/user/projects/pygame_photobooth/capture.py", line 361, in <module>
    config.load()
  File "/home/user/projects/pygame_photobooth/capture.py", line 36, in load
    fb = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: './peppercarrot.yaml'


develop is not full screen otherwise the file could be brought into master to close this issue.

**Comment by waldo323** [comment]
I verified that with the capture file from develop checked into master I am able to start the photobooth software. I will commit it to my master and then put in a pull request.
